spring:
  application:
    name: spring-boot-demo
  # redis配置
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-wait: -1 # 连接池最大阻塞时间，-1表示没有限制
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
  # 热部署生效
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
server:
  port: 8088
  tomcat: # Tomcat相关配置
